name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Build
        run: |
          export VERSAO_PACOTE=$(cat version.txt)
          GOOS=linux GOARCH=amd64 go build -ldflags="-X main.version=$VERSAO_PACOTE" -o amestris ./cmd/app/main.go
          GOOS=windows GOARCH=386 go build -ldflags="-X main.version=$VERSAO_PACOTE" -o amestris.exe ./cmd/app/main.go
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            amestris
            amestris.exe